version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub

build:
  image: testing-1.0
